#!/usr/bin/env bash
# print domain and subdomain information.

printdomain()
{
    echo -n "The subdomain $2"
    dig $2.$1 | grep "^$2.$1." |
    awk '{ print " is a " $4 " record and points to " $5 }'
}

if [ "$2" ]; then
    printdomain $1 $2
else
    printdomain $1 www
    printdomain $1 lb-01
    printdomain $1 web-01
    printdomain $1 web-02
fi
